# Generated by Django 4.0.2 on 2022-05-02 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor', models.CharField(max_length=50, null=True)),
                ('Patient', models.CharField(max_length=50)),
                ('case', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=3)),
                ('gender', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=10)),
                ('contact_email', models.CharField(max_length=100)),
                ('date_of_come', models.DateTimeField()),
                ('date_of_recover', models.DateTimeField()),
                ('description', models.TextField()),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
