# Generated by Django 4.0.2 on 2022-05-02 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_doctor_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='date_of_recover',
        ),
    ]
