# Generated by Django 4.0.2 on 2022-05-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_doctor_date_of_recover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='date_of_come',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='contact_email',
        ),
    ]
