# Generated by Django 4.0.2 on 2022-05-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_date_of_come_doctor_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='date',
            field=models.DateField(),
        ),
    ]
