# Generated by Django 4.0.2 on 2022-05-14 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_doctor_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='user',
        ),
    ]
